apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jgenato2@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          webhook:
            groupName: acme.godaddy.com
            solverName: godaddy
            config:
              authAPIKey:
                name: godaddy-api-secret
                key: key
              authAPISecret:
                name: godaddy-api-secret
                key: secret
              ttl: 600
              timeout: 120
